from __future__ import annotations

from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
DATA = ROOT / "data"
OUT = ROOT / "outputs"
RAW_DATA = DATA / "raw"
REFERENCE_DATA = DATA / "reference"
NORMALIZED_DATA = DATA / "normalized"
MANUAL_DATA = DATA / "manual"
PRIVATE_DATA = MANUAL_DATA / "private"
SOURCE_TABLES = DATA / "source_tables"

MASTER_CSV = DATA / "school_master.csv"
APPLICANT_PROFILES_CSV = DATA / "applicant_profiles.csv"
PRIVATE_APPLICANT_PROFILES_CSV = PRIVATE_DATA / "applicant_profiles.local.csv"
PREFERENCES_CSV = DATA / "user_preferences.csv"
SCENARIO_WEIGHTS_CSV = DATA / "scenario_weights.csv"
FINAL_APPLICATION_LIST_CSV = DATA / "final_application_list.csv"
AAMC_MCAT_GPA_GRID_CSV = REFERENCE_DATA / "aamc_mcat_gpa_acceptance_grid.csv"
ADMISSIONS_STATS_CSV = NORMALIZED_DATA / "admissions_stats.csv"
OFFICIAL_STATS_SOURCE_CANDIDATES_CSV = SOURCE_TABLES / "official_mcat_gpa_source_candidates.csv"
OFFICIAL_STATS_EXTRACTED_VALUES_CSV = SOURCE_TABLES / "official_mcat_gpa_extracted_values.csv"
MD_OFFICIAL_SOURCE_CANDIDATES_CSV = SOURCE_TABLES / "md_official_source_candidates.csv"
MD_OFFICIAL_EXTRACTED_STATS_CSV = SOURCE_TABLES / "md_official_extracted_stats.csv"
MD_OFFICIAL_ASSISTED_SEARCH_SEEDS_CSV = SOURCE_TABLES / "md_official_assisted_search_seeds.csv"
AACOM_DO_PROFILE_CANDIDATES_CSV = SOURCE_TABLES / "aacom_do_profile_candidates.csv"
AACOM_DO_EXTRACTED_STATS_CSV = SOURCE_TABLES / "aacom_do_extracted_stats.csv"
COST_AND_DEBT_CSV = NORMALIZED_DATA / "cost_and_debt.csv"
ADMISSIONS_POLICIES_CSV = NORMALIZED_DATA / "admissions_policies.csv"
LETTER_REQUIREMENTS_CSV = NORMALIZED_DATA / "letter_requirements.csv"
ADMISSIONS_SOURCE_QUEUE_CSV = MANUAL_DATA / "admissions_source_queue.csv"
PARTNER_INPUTS_CSV = MANUAL_DATA / "partner_inputs.csv"
SCHOOL_VISIBILITY_CSV = MANUAL_DATA / "school_visibility.csv"
SCHOOL_DOSSIERS_CSV = MANUAL_DATA / "school_dossiers.csv"
SOURCE_MATCH_OVERRIDES_CSV = MANUAL_DATA / "source_match_overrides.csv"
SOURCE_REVIEW_QUEUE_CSV = MANUAL_DATA / "source_review_queue.csv"
RANKINGS_CSV = OUT / "calculated_rankings.csv"
SCORING_METHODOLOGY_CSV = OUT / "scoring_methodology.csv"
SCORE_CONTRIBUTIONS_CSV = OUT / "score_contributions.csv"
PRIVATE_OUT = OUT / "private"
PRIVATE_RANKINGS_CSV = PRIVATE_OUT / "calculated_rankings.private.csv"
PRIVATE_SCORE_CONTRIBUTIONS_CSV = PRIVATE_OUT / "score_contributions.private.csv"
DATA_QUALITY_REPORT_CSV = OUT / "data_quality_report.csv"
SOURCE_INTEGRATION_REPORT_CSV = OUT / "source_integration_report.csv"
SOURCE_MATCH_REVIEW_CSV = OUT / "source_match_review.csv"
ADMISSIONS_STATS_CANDIDATES_CSV = OUT / "admissions_stats_candidates.csv"
ADMISSIONS_STATS_CONFLICTS_CSV = OUT / "admissions_stats_conflicts.csv"
OFFICIAL_STATS_DISCOVERY_REPORT_CSV = OUT / "official_mcat_gpa_discovery_report.csv"
OFFICIAL_STATS_REVIEW_QUEUE_CSV = OUT / "official_mcat_gpa_review_queue.csv"
OFFICIAL_STATS_COVERAGE_CSV = OUT / "official_mcat_gpa_coverage.csv"
OFFICIAL_STATS_CONFLICTS_CSV = OUT / "official_mcat_gpa_conflicts.csv"
MD_OFFICIAL_DISCOVERY_REPORT_CSV = OUT / "md_official_discovery_report.csv"
MD_OFFICIAL_REVIEW_QUEUE_CSV = OUT / "md_official_review_queue.csv"
MD_OFFICIAL_COVERAGE_CSV = OUT / "md_official_coverage.csv"
MD_OFFICIAL_CONFLICTS_CSV = OUT / "md_official_conflicts.csv"
AACOM_DO_PROFILE_COVERAGE_CSV = OUT / "aacom_do_profile_coverage.csv"
AACOM_DO_PROFILE_REVIEW_QUEUE_CSV = OUT / "aacom_do_profile_review_queue.csv"
AACOM_DO_PROFILE_CONFLICTS_CSV = OUT / "aacom_do_profile_conflicts.csv"
COST_AND_DEBT_CANDIDATES_CSV = OUT / "cost_and_debt_candidates.csv"
COST_AND_DEBT_REVIEW_CSV = OUT / "cost_and_debt_review.csv"
SITE_DIR = OUT / "site"
SITE_INDEX_HTML = SITE_DIR / "index.html"
WORKBOOK_XLSX = OUT / "med_school_ranker.xlsx"
UPLOAD_ZIP = ROOT / "med-school-ranker-upload.zip"
